//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DefaultAPI {
    /**
     Create a new blog post

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createBlogPostPostsPost(body: BlogPostCreate, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        createBlogPostPostsPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Create a new blog post
     - POST /posts/

     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func createBlogPostPostsPostWithRequestBuilder(body: BlogPostCreate) -> RequestBuilder<Void> {
        let path = "/posts/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Create a new user

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func createUserUsersPost(body: UserCreate, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        createUserUsersPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Create a new user
     - POST /users/

     - parameter body: (body)  

     - returns: RequestBuilder<Void> 
     */
    open class func createUserUsersPostWithRequestBuilder(body: UserCreate) -> RequestBuilder<Void> {
        let path = "/users/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Delete Blog Post

     - parameter postId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteBlogPostPostsPostIdDelete(postId: Any, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteBlogPostPostsPostIdDeleteWithRequestBuilder(postId: postId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete Blog Post
     - DELETE /posts/{post_id}
     - 

     - parameter postId: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func deleteBlogPostPostsPostIdDeleteWithRequestBuilder(postId: Any) -> RequestBuilder<Void> {
        var path = "/posts/{post_id}"
        let postIdPreEscape = "\(postId)"
        let postIdPostEscape = postIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{post_id}", with: postIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Delete User

     - parameter userId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func deleteUserUsersUserIdDelete(userId: Any, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        deleteUserUsersUserIdDeleteWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Delete User
     - DELETE /users/{user_id}
     - 

     - parameter userId: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func deleteUserUsersUserIdDeleteWithRequestBuilder(userId: Any) -> RequestBuilder<Void> {
        var path = "/users/{user_id}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Read Blog Post

     - parameter postId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readBlogPostPostsPostIdGet(postId: Any, completion: @escaping ((_ data: BlogPostRead?,_ error: Error?) -> Void)) {
        readBlogPostPostsPostIdGetWithRequestBuilder(postId: postId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read Blog Post
     - GET /posts/{post_id}
     - 

     - examples: [{contentType=application/json, example={
  "updated_at" : "",
  "is_published" : "",
  "created_at" : "",
  "id" : "",
  "title" : "",
  "excerpt" : "",
  "author_id" : "",
  "slug" : "",
  "content" : ""
}}]
     - parameter postId: (path)  

     - returns: RequestBuilder<BlogPostRead> 
     */
    open class func readBlogPostPostsPostIdGetWithRequestBuilder(postId: Any) -> RequestBuilder<BlogPostRead> {
        var path = "/posts/{post_id}"
        let postIdPreEscape = "\(postId)"
        let postIdPostEscape = postIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{post_id}", with: postIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<BlogPostRead>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Read Blog Posts

     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readBlogPostsPostsGet(skip: Any? = nil, limit: Any? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        readBlogPostsPostsGetWithRequestBuilder(skip: skip, limit: limit).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Read Blog Posts
     - GET /posts/
     - 

     - examples: [{contentType=application/json, example=""}]
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)

     - returns: RequestBuilder<Void> 
     */
    open class func readBlogPostsPostsGetWithRequestBuilder(skip: Any? = nil, limit: Any? = nil) -> RequestBuilder<Void> {
        let path = "/posts/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "skip": skip, 
                        "limit": limit
        ])


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Read User

     - parameter userId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readUserUsersUserIdGet(userId: Any, completion: @escaping ((_ data: UserRead?,_ error: Error?) -> Void)) {
        readUserUsersUserIdGetWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Read User
     - GET /users/{user_id}
     - 

     - examples: [{contentType=application/json, example={
  "role" : "",
  "is_active" : "",
  "last_name" : "",
  "id" : "",
  "first_name" : "",
  "email" : ""
}}]
     - parameter userId: (path)  

     - returns: RequestBuilder<UserRead> 
     */
    open class func readUserUsersUserIdGetWithRequestBuilder(userId: Any) -> RequestBuilder<UserRead> {
        var path = "/users/{user_id}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UserRead>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Read Users

     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func readUsersUsersGet(skip: Any? = nil, limit: Any? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        readUsersUsersGetWithRequestBuilder(skip: skip, limit: limit).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     Read Users
     - GET /users/
     - 

     - examples: [{contentType=application/json, example=""}]
     - parameter skip: (query)  (optional, default to 0)
     - parameter limit: (query)  (optional, default to 100)

     - returns: RequestBuilder<Void> 
     */
    open class func readUsersUsersGetWithRequestBuilder(skip: Any? = nil, limit: Any? = nil) -> RequestBuilder<Void> {
        let path = "/users/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "skip": skip, 
                        "limit": limit
        ])


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Update Blog Post

     - parameter body: (body)  
     - parameter postId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateBlogPostPostsPostIdPatch(body: BlogPostUpdate, postId: Any, completion: @escaping ((_ data: BlogPostRead?,_ error: Error?) -> Void)) {
        updateBlogPostPostsPostIdPatchWithRequestBuilder(body: body, postId: postId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update Blog Post
     - PATCH /posts/{post_id}

     - examples: [{contentType=application/json, example={
  "updated_at" : "",
  "is_published" : "",
  "created_at" : "",
  "id" : "",
  "title" : "",
  "excerpt" : "",
  "author_id" : "",
  "slug" : "",
  "content" : ""
}}]
     - parameter body: (body)  
     - parameter postId: (path)  

     - returns: RequestBuilder<BlogPostRead> 
     */
    open class func updateBlogPostPostsPostIdPatchWithRequestBuilder(body: BlogPostUpdate, postId: Any) -> RequestBuilder<BlogPostRead> {
        var path = "/posts/{post_id}"
        let postIdPreEscape = "\(postId)"
        let postIdPostEscape = postIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{post_id}", with: postIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<BlogPostRead>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**
     Update User

     - parameter body: (body)  
     - parameter userId: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func updateUserUsersUserIdPatch(body: UserUpdate, userId: Any, completion: @escaping ((_ data: UserRead?,_ error: Error?) -> Void)) {
        updateUserUsersUserIdPatchWithRequestBuilder(body: body, userId: userId).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Update User
     - PATCH /users/{user_id}
     - 

     - examples: [{contentType=application/json, example={
  "role" : "",
  "is_active" : "",
  "last_name" : "",
  "id" : "",
  "first_name" : "",
  "email" : ""
}}]
     - parameter body: (body)  
     - parameter userId: (path)  

     - returns: RequestBuilder<UserRead> 
     */
    open class func updateUserUsersUserIdPatchWithRequestBuilder(body: UserUpdate, userId: Any) -> RequestBuilder<UserRead> {
        var path = "/users/{user_id}"
        let userIdPreEscape = "\(userId)"
        let userIdPostEscape = userIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{user_id}", with: userIdPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UserRead>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
