/// <reference path="./custom.d.ts" />
// tslint:disable
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as url from "url";
import * as isomorphicFetch from "isomorphic-fetch";
import { Configuration } from "./configuration";

const BASE_PATH = "/".replace(/\/+$/, "");

/**
 *
 * @export
 */
export const COLLECTION_FORMATS = {
    csv: ",",
    ssv: " ",
    tsv: "\t",
    pipes: "|",
};

/**
 *
 * @export
 * @interface FetchAPI
 */
export interface FetchAPI {
    (url: string, init?: any): Promise<Response>;
}

/**
 *
 * @export
 * @interface FetchArgs
 */
export interface FetchArgs {
    url: string;
    options: any;
}

/**
 *
 * @export
 * @class BaseAPI
 */
export class BaseAPI {
    protected configuration: Configuration;

    constructor(configuration?: Configuration, protected basePath: string = BASE_PATH, protected fetch: FetchAPI = isomorphicFetch) {
        if (configuration) {
            this.configuration = configuration;
            this.basePath = configuration.basePath || this.basePath;
        }
    }
}

/**
 *
 * @export
 * @class RequiredError
 * @extends {Error}
 */
export class RequiredError extends Error {
    name = "RequiredError"
    constructor(public field: string, msg?: string) {
        super(msg);
    }
}

/**
 * Request body for creating a new blog post.
 * @export
 * @interface BlogPostCreate
 */
export interface BlogPostCreate {
    /**
     * Post title
     * @type {any}
     * @memberof BlogPostCreate
     */
    title: any;
    /**
     * URL-friendly slug (kebab-case)
     * @type {any}
     * @memberof BlogPostCreate
     */
    slug: any;
    /**
     * Optional short excerpt/teaser
     * @type {any}
     * @memberof BlogPostCreate
     */
    excerpt?: any;
    /**
     * Full markdown/HTML content
     * @type {any}
     * @memberof BlogPostCreate
     */
    content: any;
    /**
     * Publish immediately?
     * @type {any}
     * @memberof BlogPostCreate
     */
    isPublished?: any;
    /**
     * Author UUID
     * @type {any}
     * @memberof BlogPostCreate
     */
    authorId: any;
}
/**
 * Response model - no sensitive data.
 * @export
 * @interface BlogPostRead
 */
export interface BlogPostRead {
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    id: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    title: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    slug: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    excerpt?: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    content: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    isPublished: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    authorId: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    createdAt: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostRead
     */
    updatedAt: any;
}
/**
 * Partial update for blog posts (all fields optional).
 * @export
 * @interface BlogPostUpdate
 */
export interface BlogPostUpdate {
    /**
     * 
     * @type {any}
     * @memberof BlogPostUpdate
     */
    title?: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostUpdate
     */
    slug?: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostUpdate
     */
    excerpt?: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostUpdate
     */
    content?: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostUpdate
     */
    isPublished?: any;
    /**
     * 
     * @type {any}
     * @memberof BlogPostUpdate
     */
    authorId?: any;
}
/**
 * Used for string-only error messages (404, 409, custom errors)
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {any}
     * @memberof ErrorResponse
     */
    detail: any;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {any}
     * @memberof HTTPValidationError
     */
    detail: any;
}
/**
 * 
 * @export
 * @interface UserCreate
 */
export interface UserCreate {
    /**
     * 
     * @type {any}
     * @memberof UserCreate
     */
    email: any;
    /**
     * 
     * @type {any}
     * @memberof UserCreate
     */
    password: any;
    /**
     * 
     * @type {any}
     * @memberof UserCreate
     */
    firstName?: any;
    /**
     * 
     * @type {any}
     * @memberof UserCreate
     */
    lastName?: any;
}
/**
 * User model for API responses - excludes password field from serialization.
 * @export
 * @interface UserRead
 */
export interface UserRead {
    /**
     * 
     * @type {any}
     * @memberof UserRead
     */
    id: any;
    /**
     * 
     * @type {any}
     * @memberof UserRead
     */
    email: any;
    /**
     * 
     * @type {UserRole}
     * @memberof UserRead
     */
    role: UserRole;
    /**
     * 
     * @type {any}
     * @memberof UserRead
     */
    isActive: any;
    /**
     * 
     * @type {any}
     * @memberof UserRead
     */
    firstName?: any;
    /**
     * 
     * @type {any}
     * @memberof UserRead
     */
    lastName?: any;
}
/**
 * 
 * @export
 * @enum {string}
 */
export enum UserRole {
    USER = <any> 'USER',
    ADMIN = <any> 'ADMIN'
}
/**
 * 
 * @export
 * @interface UserUpdate
 */
export interface UserUpdate {
    /**
     * 
     * @type {any}
     * @memberof UserUpdate
     */
    email?: any;
    /**
     * 
     * @type {any}
     * @memberof UserUpdate
     */
    password?: any;
    /**
     * 
     * @type {any}
     * @memberof UserUpdate
     */
    role?: any;
    /**
     * 
     * @type {any}
     * @memberof UserUpdate
     */
    isActive?: any;
    /**
     * 
     * @type {any}
     * @memberof UserUpdate
     */
    firstName?: any;
    /**
     * 
     * @type {any}
     * @memberof UserUpdate
     */
    lastName?: any;
}
/**
 * DefaultApi - fetch parameter creator
 * @export
 */
export const DefaultApiFetchParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a new blog post.          **Idempotent**: If a post with the same slug already exists, returns that post (200 OK).          **Validation:**     - Title: 1-200 chars, ASCII alphanumeric + basic punctuation     - Slug: 3-100 chars, kebab-case (lowercase-with-hyphens)     - Content: 10-10000 chars
         * @summary Create a new blog post
         * @param {BlogPostCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBlogPostPostsPost(body: BlogPostCreate, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createBlogPostPostsPost.');
            }
            const localVarPath = `/posts/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"BlogPostCreate" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a new user with the provided details.          **Idempotent**: If a user with the same email already exists, returns the existing user (200 OK).          **Password Requirements:**     - Length: 8-128 characters     - Allowed characters: A-Z, a-z, 0-9, @$!%*?&
         * @summary Create a new user
         * @param {UserCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserUsersPost(body: UserCreate, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling createUserUsersPost.');
            }
            const localVarPath = `/users/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'POST' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UserCreate" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Blog Post
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBlogPostPostsPostIdDelete(postId: any, options: any = {}): FetchArgs {
            // verify required parameter 'postId' is not null or undefined
            if (postId === null || postId === undefined) {
                throw new RequiredError('postId','Required parameter postId was null or undefined when calling deleteBlogPostPostsPostIdDelete.');
            }
            const localVarPath = `/posts/{post_id}`
                .replace(`{${"post_id"}}`, encodeURIComponent(String(postId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete User
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserUsersUserIdDelete(userId: any, options: any = {}): FetchArgs {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling deleteUserUsersUserIdDelete.');
            }
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'DELETE' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read Blog Post
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBlogPostPostsPostIdGet(postId: any, options: any = {}): FetchArgs {
            // verify required parameter 'postId' is not null or undefined
            if (postId === null || postId === undefined) {
                throw new RequiredError('postId','Required parameter postId was null or undefined when calling readBlogPostPostsPostIdGet.');
            }
            const localVarPath = `/posts/{post_id}`
                .replace(`{${"post_id"}}`, encodeURIComponent(String(postId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read Blog Posts
         * @param {any} [skip] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBlogPostsPostsGet(skip?: any, limit?: any, options: any = {}): FetchArgs {
            const localVarPath = `/posts/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read User
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUserUsersUserIdGet(userId: any, options: any = {}): FetchArgs {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling readUserUsersUserIdGet.');
            }
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Read Users
         * @param {any} [skip] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUsersUsersGet(skip?: any, limit?: any, options: any = {}): FetchArgs {
            const localVarPath = `/users/`;
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'GET' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skip !== undefined) {
                localVarQueryParameter['skip'] = skip;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Update blog post - NO slug uniqueness check to avoid 409.
         * @summary Update Blog Post
         * @param {BlogPostUpdate} body 
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBlogPostPostsPostIdPatch(body: BlogPostUpdate, postId: any, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateBlogPostPostsPostIdPatch.');
            }
            // verify required parameter 'postId' is not null or undefined
            if (postId === null || postId === undefined) {
                throw new RequiredError('postId','Required parameter postId was null or undefined when calling updateBlogPostPostsPostIdPatch.');
            }
            const localVarPath = `/posts/{post_id}`
                .replace(`{${"post_id"}}`, encodeURIComponent(String(postId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"BlogPostUpdate" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update User
         * @param {UserUpdate} body 
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserUsersUserIdPatch(body: UserUpdate, userId: any, options: any = {}): FetchArgs {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling updateUserUsersUserIdPatch.');
            }
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling updateUserUsersUserIdPatch.');
            }
            const localVarPath = `/users/{user_id}`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            const localVarUrlObj = url.parse(localVarPath, true);
            const localVarRequestOptions = Object.assign({ method: 'PATCH' }, options);
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            localVarUrlObj.query = Object.assign({}, localVarUrlObj.query, localVarQueryParameter, options.query);
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            localVarUrlObj.search = null;
            localVarRequestOptions.headers = Object.assign({}, localVarHeaderParameter, options.headers);
            const needsSerialization = (<any>"UserUpdate" !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.body =  needsSerialization ? JSON.stringify(body || {}) : (body || "");

            return {
                url: url.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Create a new blog post.          **Idempotent**: If a post with the same slug already exists, returns that post (200 OK).          **Validation:**     - Title: 1-200 chars, ASCII alphanumeric + basic punctuation     - Slug: 3-100 chars, kebab-case (lowercase-with-hyphens)     - Content: 10-10000 chars
         * @summary Create a new blog post
         * @param {BlogPostCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBlogPostPostsPost(body: BlogPostCreate, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).createBlogPostPostsPost(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Create a new user with the provided details.          **Idempotent**: If a user with the same email already exists, returns the existing user (200 OK).          **Password Requirements:**     - Length: 8-128 characters     - Allowed characters: A-Z, a-z, 0-9, @$!%*?&
         * @summary Create a new user
         * @param {UserCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserUsersPost(body: UserCreate, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).createUserUsersPost(body, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Delete Blog Post
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBlogPostPostsPostIdDelete(postId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).deleteBlogPostPostsPostIdDelete(postId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Delete User
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserUsersUserIdDelete(userId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<Response> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).deleteUserUsersUserIdDelete(userId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response;
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Read Blog Post
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBlogPostPostsPostIdGet(postId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<BlogPostRead> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).readBlogPostPostsPostIdGet(postId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Read Blog Posts
         * @param {any} [skip] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBlogPostsPostsGet(skip?: any, limit?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).readBlogPostsPostsGet(skip, limit, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Read User
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUserUsersUserIdGet(userId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<UserRead> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).readUserUsersUserIdGet(userId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Read Users
         * @param {any} [skip] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUsersUsersGet(skip?: any, limit?: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<any> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).readUsersUsersGet(skip, limit, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * Update blog post - NO slug uniqueness check to avoid 409.
         * @summary Update Blog Post
         * @param {BlogPostUpdate} body 
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBlogPostPostsPostIdPatch(body: BlogPostUpdate, postId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<BlogPostRead> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).updateBlogPostPostsPostIdPatch(body, postId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
        /**
         * 
         * @summary Update User
         * @param {UserUpdate} body 
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserUsersUserIdPatch(body: UserUpdate, userId: any, options?: any): (fetch?: FetchAPI, basePath?: string) => Promise<UserRead> {
            const localVarFetchArgs = DefaultApiFetchParamCreator(configuration).updateUserUsersUserIdPatch(body, userId, options);
            return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
                return fetch(basePath + localVarFetchArgs.url, localVarFetchArgs.options).then((response) => {
                    if (response.status >= 200 && response.status < 300) {
                        return response.json();
                    } else {
                        throw response;
                    }
                });
            };
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, fetch?: FetchAPI, basePath?: string) {
    return {
        /**
         * Create a new blog post.          **Idempotent**: If a post with the same slug already exists, returns that post (200 OK).          **Validation:**     - Title: 1-200 chars, ASCII alphanumeric + basic punctuation     - Slug: 3-100 chars, kebab-case (lowercase-with-hyphens)     - Content: 10-10000 chars
         * @summary Create a new blog post
         * @param {BlogPostCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createBlogPostPostsPost(body: BlogPostCreate, options?: any) {
            return DefaultApiFp(configuration).createBlogPostPostsPost(body, options)(fetch, basePath);
        },
        /**
         * Create a new user with the provided details.          **Idempotent**: If a user with the same email already exists, returns the existing user (200 OK).          **Password Requirements:**     - Length: 8-128 characters     - Allowed characters: A-Z, a-z, 0-9, @$!%*?&
         * @summary Create a new user
         * @param {UserCreate} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUserUsersPost(body: UserCreate, options?: any) {
            return DefaultApiFp(configuration).createUserUsersPost(body, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Delete Blog Post
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBlogPostPostsPostIdDelete(postId: any, options?: any) {
            return DefaultApiFp(configuration).deleteBlogPostPostsPostIdDelete(postId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Delete User
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUserUsersUserIdDelete(userId: any, options?: any) {
            return DefaultApiFp(configuration).deleteUserUsersUserIdDelete(userId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Read Blog Post
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBlogPostPostsPostIdGet(postId: any, options?: any) {
            return DefaultApiFp(configuration).readBlogPostPostsPostIdGet(postId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Read Blog Posts
         * @param {any} [skip] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readBlogPostsPostsGet(skip?: any, limit?: any, options?: any) {
            return DefaultApiFp(configuration).readBlogPostsPostsGet(skip, limit, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Read User
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUserUsersUserIdGet(userId: any, options?: any) {
            return DefaultApiFp(configuration).readUserUsersUserIdGet(userId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Read Users
         * @param {any} [skip] 
         * @param {any} [limit] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        readUsersUsersGet(skip?: any, limit?: any, options?: any) {
            return DefaultApiFp(configuration).readUsersUsersGet(skip, limit, options)(fetch, basePath);
        },
        /**
         * Update blog post - NO slug uniqueness check to avoid 409.
         * @summary Update Blog Post
         * @param {BlogPostUpdate} body 
         * @param {any} postId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateBlogPostPostsPostIdPatch(body: BlogPostUpdate, postId: any, options?: any) {
            return DefaultApiFp(configuration).updateBlogPostPostsPostIdPatch(body, postId, options)(fetch, basePath);
        },
        /**
         * 
         * @summary Update User
         * @param {UserUpdate} body 
         * @param {any} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserUsersUserIdPatch(body: UserUpdate, userId: any, options?: any) {
            return DefaultApiFp(configuration).updateUserUsersUserIdPatch(body, userId, options)(fetch, basePath);
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Create a new blog post.          **Idempotent**: If a post with the same slug already exists, returns that post (200 OK).          **Validation:**     - Title: 1-200 chars, ASCII alphanumeric + basic punctuation     - Slug: 3-100 chars, kebab-case (lowercase-with-hyphens)     - Content: 10-10000 chars
     * @summary Create a new blog post
     * @param {BlogPostCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createBlogPostPostsPost(body: BlogPostCreate, options?: any) {
        return DefaultApiFp(this.configuration).createBlogPostPostsPost(body, options)(this.fetch, this.basePath);
    }

    /**
     * Create a new user with the provided details.          **Idempotent**: If a user with the same email already exists, returns the existing user (200 OK).          **Password Requirements:**     - Length: 8-128 characters     - Allowed characters: A-Z, a-z, 0-9, @$!%*?&
     * @summary Create a new user
     * @param {UserCreate} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createUserUsersPost(body: UserCreate, options?: any) {
        return DefaultApiFp(this.configuration).createUserUsersPost(body, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Delete Blog Post
     * @param {any} postId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteBlogPostPostsPostIdDelete(postId: any, options?: any) {
        return DefaultApiFp(this.configuration).deleteBlogPostPostsPostIdDelete(postId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Delete User
     * @param {any} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public deleteUserUsersUserIdDelete(userId: any, options?: any) {
        return DefaultApiFp(this.configuration).deleteUserUsersUserIdDelete(userId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Read Blog Post
     * @param {any} postId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readBlogPostPostsPostIdGet(postId: any, options?: any) {
        return DefaultApiFp(this.configuration).readBlogPostPostsPostIdGet(postId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Read Blog Posts
     * @param {any} [skip] 
     * @param {any} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readBlogPostsPostsGet(skip?: any, limit?: any, options?: any) {
        return DefaultApiFp(this.configuration).readBlogPostsPostsGet(skip, limit, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Read User
     * @param {any} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readUserUsersUserIdGet(userId: any, options?: any) {
        return DefaultApiFp(this.configuration).readUserUsersUserIdGet(userId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Read Users
     * @param {any} [skip] 
     * @param {any} [limit] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public readUsersUsersGet(skip?: any, limit?: any, options?: any) {
        return DefaultApiFp(this.configuration).readUsersUsersGet(skip, limit, options)(this.fetch, this.basePath);
    }

    /**
     * Update blog post - NO slug uniqueness check to avoid 409.
     * @summary Update Blog Post
     * @param {BlogPostUpdate} body 
     * @param {any} postId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateBlogPostPostsPostIdPatch(body: BlogPostUpdate, postId: any, options?: any) {
        return DefaultApiFp(this.configuration).updateBlogPostPostsPostIdPatch(body, postId, options)(this.fetch, this.basePath);
    }

    /**
     * 
     * @summary Update User
     * @param {UserUpdate} body 
     * @param {any} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public updateUserUsersUserIdPatch(body: UserUpdate, userId: any, options?: any) {
        return DefaultApiFp(this.configuration).updateUserUsersUserIdPatch(body, userId, options)(this.fetch, this.basePath);
    }

}
