/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

import * as api from "./api"
import { Configuration } from "./configuration"

const config: Configuration = {}

describe("DefaultApi", () => {
  let instance: api.DefaultApi
  beforeEach(function() {
    instance = new api.DefaultApi(config)
  });

  test("createBlogPostPostsPost", () => {
    const body: api.BlogPostCreate = undefined
    return expect(instance.createBlogPostPostsPost(body, {})).resolves.toBe(null)
  })
  test("createUserUsersPost", () => {
    const body: api.UserCreate = undefined
    return expect(instance.createUserUsersPost(body, {})).resolves.toBe(null)
  })
  test("deleteBlogPostPostsPostIdDelete", () => {
    const postId: any = undefined
    return expect(instance.deleteBlogPostPostsPostIdDelete(postId, {})).resolves.toBe(null)
  })
  test("deleteUserUsersUserIdDelete", () => {
    const userId: any = undefined
    return expect(instance.deleteUserUsersUserIdDelete(userId, {})).resolves.toBe(null)
  })
  test("readBlogPostPostsPostIdGet", () => {
    const postId: any = undefined
    return expect(instance.readBlogPostPostsPostIdGet(postId, {})).resolves.toBe(null)
  })
  test("readBlogPostsPostsGet", () => {
    const skip: any = undefined
    const limit: any = undefined
    return expect(instance.readBlogPostsPostsGet(skip, limit, {})).resolves.toBe(null)
  })
  test("readUserUsersUserIdGet", () => {
    const userId: any = undefined
    return expect(instance.readUserUsersUserIdGet(userId, {})).resolves.toBe(null)
  })
  test("readUsersUsersGet", () => {
    const skip: any = undefined
    const limit: any = undefined
    return expect(instance.readUsersUsersGet(skip, limit, {})).resolves.toBe(null)
  })
  test("updateBlogPostPostsPostIdPatch", () => {
    const body: api.BlogPostUpdate = undefined
    const postId: any = undefined
    return expect(instance.updateBlogPostPostsPostIdPatch(body, postId, {})).resolves.toBe(null)
  })
  test("updateUserUsersUserIdPatch", () => {
    const body: api.UserUpdate = undefined
    const userId: any = undefined
    return expect(instance.updateUserUsersUserIdPatch(body, userId, {})).resolves.toBe(null)
  })
})

