//
// BlogPostCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Request body for creating a new blog post. */

public struct BlogPostCreate: Codable {

    /** Post title */
    public var title: Any
    /** URL-friendly slug (kebab-case) */
    public var slug: Any
    /** Optional short excerpt/teaser */
    public var excerpt: Any?
    /** Full markdown/HTML content */
    public var content: Any
    /** Publish immediately? */
    public var isPublished: Any?
    /** Author UUID */
    public var authorId: Any

    public init(title: Any, slug: Any, excerpt: Any? = nil, content: Any, isPublished: Any? = nil, authorId: Any) {
        self.title = title
        self.slug = slug
        self.excerpt = excerpt
        self.content = content
        self.isPublished = isPublished
        self.authorId = authorId
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case slug
        case excerpt
        case content
        case isPublished = "is_published"
        case authorId = "author_id"
    }

}
