//
// BlogPostRead.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Response model - no sensitive data. */

public struct BlogPostRead: Codable {

    public var _id: Any
    public var title: Any
    public var slug: Any
    public var excerpt: Any?
    public var content: Any
    public var isPublished: Any
    public var authorId: Any
    public var createdAt: Any
    public var updatedAt: Any

    public init(_id: Any, title: Any, slug: Any, excerpt: Any? = nil, content: Any, isPublished: Any, authorId: Any, createdAt: Any, updatedAt: Any) {
        self._id = _id
        self.title = title
        self.slug = slug
        self.excerpt = excerpt
        self.content = content
        self.isPublished = isPublished
        self.authorId = authorId
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case slug
        case excerpt
        case content
        case isPublished = "is_published"
        case authorId = "author_id"
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }

}
