//
// BlogPostUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Partial update for blog posts (all fields optional). */

public struct BlogPostUpdate: Codable {

    public var title: Any?
    public var slug: Any?
    public var excerpt: Any?
    public var content: Any?
    public var isPublished: Any?
    public var authorId: Any?

    public init(title: Any? = nil, slug: Any? = nil, excerpt: Any? = nil, content: Any? = nil, isPublished: Any? = nil, authorId: Any? = nil) {
        self.title = title
        self.slug = slug
        self.excerpt = excerpt
        self.content = content
        self.isPublished = isPublished
        self.authorId = authorId
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case slug
        case excerpt
        case content
        case isPublished = "is_published"
        case authorId = "author_id"
    }

}
