//
// ModelErrorResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Used for string-only error messages (404, 409, custom errors) */

public struct ModelErrorResponse: Codable {

    public var detail: Any

    public init(detail: Any) {
        self.detail = detail
    }


}
