//
// UserUpdate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserUpdate: Codable {

    public var email: Any?
    public var password: Any?
    public var role: Any?
    public var isActive: Any?
    public var firstName: Any?
    public var lastName: Any?

    public init(email: Any? = nil, password: Any? = nil, role: Any? = nil, isActive: Any? = nil, firstName: Any? = nil, lastName: Any? = nil) {
        self.email = email
        self.password = password
        self.role = role
        self.isActive = isActive
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey { 
        case email
        case password
        case role
        case isActive = "is_active"
        case firstName = "first_name"
        case lastName = "last_name"
    }

}
