//
// UserCreate.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserCreate: Codable {

    public var email: Any
    public var password: Any
    public var firstName: Any?
    public var lastName: Any?

    public init(email: Any, password: Any, firstName: Any? = nil, lastName: Any? = nil) {
        self.email = email
        self.password = password
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey { 
        case email
        case password
        case firstName = "first_name"
        case lastName = "last_name"
    }

}
