//
// UserRole.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public enum UserRole: Object, Codable {
    case user = "USER"
    case admin = "ADMIN"
}