//
// UserRead.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** User model for API responses - excludes password field from serialization. */

public struct UserRead: Codable {

    public var _id: Any
    public var email: Any
    public var role: UserRole
    public var isActive: Any
    public var firstName: Any?
    public var lastName: Any?

    public init(_id: Any, email: Any, role: UserRole, isActive: Any, firstName: Any? = nil, lastName: Any? = nil) {
        self._id = _id
        self.email = email
        self.role = role
        self.isActive = isActive
        self.firstName = firstName
        self.lastName = lastName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case email
        case role
        case isActive = "is_active"
        case firstName = "first_name"
        case lastName = "last_name"
    }

}
