# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BlogPostRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'title': 'object',
        'slug': 'object',
        'excerpt': 'object',
        'content': 'object',
        'is_published': 'object',
        'author_id': 'object',
        'created_at': 'object',
        'updated_at': 'object'
    }

    attribute_map = {
        'id': 'id',
        'title': 'title',
        'slug': 'slug',
        'excerpt': 'excerpt',
        'content': 'content',
        'is_published': 'is_published',
        'author_id': 'author_id',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, title=None, slug=None, excerpt=None, content=None, is_published=None, author_id=None, created_at=None, updated_at=None):  # noqa: E501
        """BlogPostRead - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._title = None
        self._slug = None
        self._excerpt = None
        self._content = None
        self._is_published = None
        self._author_id = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None
        self.id = id
        self.title = title
        self.slug = slug
        if excerpt is not None:
            self.excerpt = excerpt
        self.content = content
        self.is_published = is_published
        self.author_id = author_id
        self.created_at = created_at
        self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this BlogPostRead.  # noqa: E501


        :return: The id of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this BlogPostRead.


        :param id: The id of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self):
        """Gets the title of this BlogPostRead.  # noqa: E501


        :return: The title of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BlogPostRead.


        :param title: The title of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def slug(self):
        """Gets the slug of this BlogPostRead.  # noqa: E501


        :return: The slug of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this BlogPostRead.


        :param slug: The slug of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if slug is None:
            raise ValueError("Invalid value for `slug`, must not be `None`")  # noqa: E501

        self._slug = slug

    @property
    def excerpt(self):
        """Gets the excerpt of this BlogPostRead.  # noqa: E501


        :return: The excerpt of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._excerpt

    @excerpt.setter
    def excerpt(self, excerpt):
        """Sets the excerpt of this BlogPostRead.


        :param excerpt: The excerpt of this BlogPostRead.  # noqa: E501
        :type: object
        """

        self._excerpt = excerpt

    @property
    def content(self):
        """Gets the content of this BlogPostRead.  # noqa: E501


        :return: The content of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this BlogPostRead.


        :param content: The content of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if content is None:
            raise ValueError("Invalid value for `content`, must not be `None`")  # noqa: E501

        self._content = content

    @property
    def is_published(self):
        """Gets the is_published of this BlogPostRead.  # noqa: E501


        :return: The is_published of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._is_published

    @is_published.setter
    def is_published(self, is_published):
        """Sets the is_published of this BlogPostRead.


        :param is_published: The is_published of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if is_published is None:
            raise ValueError("Invalid value for `is_published`, must not be `None`")  # noqa: E501

        self._is_published = is_published

    @property
    def author_id(self):
        """Gets the author_id of this BlogPostRead.  # noqa: E501


        :return: The author_id of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id):
        """Sets the author_id of this BlogPostRead.


        :param author_id: The author_id of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if author_id is None:
            raise ValueError("Invalid value for `author_id`, must not be `None`")  # noqa: E501

        self._author_id = author_id

    @property
    def created_at(self):
        """Gets the created_at of this BlogPostRead.  # noqa: E501


        :return: The created_at of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this BlogPostRead.


        :param created_at: The created_at of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if created_at is None:
            raise ValueError("Invalid value for `created_at`, must not be `None`")  # noqa: E501

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this BlogPostRead.  # noqa: E501


        :return: The updated_at of this BlogPostRead.  # noqa: E501
        :rtype: object
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this BlogPostRead.


        :param updated_at: The updated_at of this BlogPostRead.  # noqa: E501
        :type: object
        """
        if updated_at is None:
            raise ValueError("Invalid value for `updated_at`, must not be `None`")  # noqa: E501

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BlogPostRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlogPostRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
