# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BlogPostUpdate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'title': 'object',
        'slug': 'object',
        'excerpt': 'object',
        'content': 'object',
        'is_published': 'object',
        'author_id': 'object'
    }

    attribute_map = {
        'title': 'title',
        'slug': 'slug',
        'excerpt': 'excerpt',
        'content': 'content',
        'is_published': 'is_published',
        'author_id': 'author_id'
    }

    def __init__(self, title=None, slug=None, excerpt=None, content=None, is_published=None, author_id=None):  # noqa: E501
        """BlogPostUpdate - a model defined in Swagger"""  # noqa: E501
        self._title = None
        self._slug = None
        self._excerpt = None
        self._content = None
        self._is_published = None
        self._author_id = None
        self.discriminator = None
        if title is not None:
            self.title = title
        if slug is not None:
            self.slug = slug
        if excerpt is not None:
            self.excerpt = excerpt
        if content is not None:
            self.content = content
        if is_published is not None:
            self.is_published = is_published
        if author_id is not None:
            self.author_id = author_id

    @property
    def title(self):
        """Gets the title of this BlogPostUpdate.  # noqa: E501


        :return: The title of this BlogPostUpdate.  # noqa: E501
        :rtype: object
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this BlogPostUpdate.


        :param title: The title of this BlogPostUpdate.  # noqa: E501
        :type: object
        """

        self._title = title

    @property
    def slug(self):
        """Gets the slug of this BlogPostUpdate.  # noqa: E501


        :return: The slug of this BlogPostUpdate.  # noqa: E501
        :rtype: object
        """
        return self._slug

    @slug.setter
    def slug(self, slug):
        """Sets the slug of this BlogPostUpdate.


        :param slug: The slug of this BlogPostUpdate.  # noqa: E501
        :type: object
        """

        self._slug = slug

    @property
    def excerpt(self):
        """Gets the excerpt of this BlogPostUpdate.  # noqa: E501


        :return: The excerpt of this BlogPostUpdate.  # noqa: E501
        :rtype: object
        """
        return self._excerpt

    @excerpt.setter
    def excerpt(self, excerpt):
        """Sets the excerpt of this BlogPostUpdate.


        :param excerpt: The excerpt of this BlogPostUpdate.  # noqa: E501
        :type: object
        """

        self._excerpt = excerpt

    @property
    def content(self):
        """Gets the content of this BlogPostUpdate.  # noqa: E501


        :return: The content of this BlogPostUpdate.  # noqa: E501
        :rtype: object
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this BlogPostUpdate.


        :param content: The content of this BlogPostUpdate.  # noqa: E501
        :type: object
        """

        self._content = content

    @property
    def is_published(self):
        """Gets the is_published of this BlogPostUpdate.  # noqa: E501


        :return: The is_published of this BlogPostUpdate.  # noqa: E501
        :rtype: object
        """
        return self._is_published

    @is_published.setter
    def is_published(self, is_published):
        """Sets the is_published of this BlogPostUpdate.


        :param is_published: The is_published of this BlogPostUpdate.  # noqa: E501
        :type: object
        """

        self._is_published = is_published

    @property
    def author_id(self):
        """Gets the author_id of this BlogPostUpdate.  # noqa: E501


        :return: The author_id of this BlogPostUpdate.  # noqa: E501
        :rtype: object
        """
        return self._author_id

    @author_id.setter
    def author_id(self, author_id):
        """Sets the author_id of this BlogPostUpdate.


        :param author_id: The author_id of this BlogPostUpdate.  # noqa: E501
        :type: object
        """

        self._author_id = author_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BlogPostUpdate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BlogPostUpdate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
