# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserRead(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'object',
        'email': 'object',
        'role': 'UserRole',
        'is_active': 'object',
        'first_name': 'object',
        'last_name': 'object'
    }

    attribute_map = {
        'id': 'id',
        'email': 'email',
        'role': 'role',
        'is_active': 'is_active',
        'first_name': 'first_name',
        'last_name': 'last_name'
    }

    def __init__(self, id=None, email=None, role=None, is_active=None, first_name=None, last_name=None):  # noqa: E501
        """UserRead - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._email = None
        self._role = None
        self._is_active = None
        self._first_name = None
        self._last_name = None
        self.discriminator = None
        self.id = id
        self.email = email
        self.role = role
        self.is_active = is_active
        if first_name is not None:
            self.first_name = first_name
        if last_name is not None:
            self.last_name = last_name

    @property
    def id(self):
        """Gets the id of this UserRead.  # noqa: E501


        :return: The id of this UserRead.  # noqa: E501
        :rtype: object
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserRead.


        :param id: The id of this UserRead.  # noqa: E501
        :type: object
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def email(self):
        """Gets the email of this UserRead.  # noqa: E501


        :return: The email of this UserRead.  # noqa: E501
        :rtype: object
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserRead.


        :param email: The email of this UserRead.  # noqa: E501
        :type: object
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def role(self):
        """Gets the role of this UserRead.  # noqa: E501


        :return: The role of this UserRead.  # noqa: E501
        :rtype: UserRole
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this UserRead.


        :param role: The role of this UserRead.  # noqa: E501
        :type: UserRole
        """
        if role is None:
            raise ValueError("Invalid value for `role`, must not be `None`")  # noqa: E501

        self._role = role

    @property
    def is_active(self):
        """Gets the is_active of this UserRead.  # noqa: E501


        :return: The is_active of this UserRead.  # noqa: E501
        :rtype: object
        """
        return self._is_active

    @is_active.setter
    def is_active(self, is_active):
        """Sets the is_active of this UserRead.


        :param is_active: The is_active of this UserRead.  # noqa: E501
        :type: object
        """
        if is_active is None:
            raise ValueError("Invalid value for `is_active`, must not be `None`")  # noqa: E501

        self._is_active = is_active

    @property
    def first_name(self):
        """Gets the first_name of this UserRead.  # noqa: E501


        :return: The first_name of this UserRead.  # noqa: E501
        :rtype: object
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name):
        """Sets the first_name of this UserRead.


        :param first_name: The first_name of this UserRead.  # noqa: E501
        :type: object
        """

        self._first_name = first_name

    @property
    def last_name(self):
        """Gets the last_name of this UserRead.  # noqa: E501


        :return: The last_name of this UserRead.  # noqa: E501
        :rtype: object
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name):
        """Sets the last_name of this UserRead.


        :param last_name: The last_name of this UserRead.  # noqa: E501
        :type: object
        """

        self._last_name = last_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserRead, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserRead):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
