# coding: utf-8

"""
    FastAPI

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_blog_post_posts_post(self):
        """Test case for create_blog_post_posts_post

        Create a new blog post  # noqa: E501
        """
        pass

    def test_create_user_users_post(self):
        """Test case for create_user_users_post

        Create a new user  # noqa: E501
        """
        pass

    def test_delete_blog_post_posts_post_id_delete(self):
        """Test case for delete_blog_post_posts_post_id_delete

        Delete Blog Post  # noqa: E501
        """
        pass

    def test_delete_user_users_user_id_delete(self):
        """Test case for delete_user_users_user_id_delete

        Delete User  # noqa: E501
        """
        pass

    def test_read_blog_post_posts_post_id_get(self):
        """Test case for read_blog_post_posts_post_id_get

        Read Blog Post  # noqa: E501
        """
        pass

    def test_read_blog_posts_posts_get(self):
        """Test case for read_blog_posts_posts_get

        Read Blog Posts  # noqa: E501
        """
        pass

    def test_read_user_users_user_id_get(self):
        """Test case for read_user_users_user_id_get

        Read User  # noqa: E501
        """
        pass

    def test_read_users_users_get(self):
        """Test case for read_users_users_get

        Read Users  # noqa: E501
        """
        pass

    def test_update_blog_post_posts_post_id_patch(self):
        """Test case for update_blog_post_posts_post_id_patch

        Update Blog Post  # noqa: E501
        """
        pass

    def test_update_user_users_user_id_patch(self):
        """Test case for update_user_users_user_id_patch

        Update User  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
